wip

diff --git a/dist/images/kubectl-ko b/dist/images/kubectl-ko
--- a/dist/images/kubectl-ko
+++ b/dist/images/kubectl-ko
@@ -539,15 +539,14 @@ checkDeployment(){
 }
 
 checkKubeProxy(){
-  if kubectl get ds -n kube-system --no-headers -o custom-columns=NAME:.metadata.name | grep -qw ^kube-proxy; then
+  if kubectl get ds -n kube-system --no-headers -o custom-columns=NAME:.metadata.name | grep -q '^kube-proxy$'; then
     checkDaemonSet kube-proxy
   else
     nodeIps=`kubectl get node -o wide | grep -v "INTERNAL-IP" | awk '{print $6}'`
-    for node in $nodeIps
-    do
-      healthResult=`curl -g -6 -sL -w %{http_code} http://[$node]:10256/healthz -o /dev/null | grep -v 200 || true`
+    for node in $nodeIps; do
+      healthResult=`curl -g -6 -sL -m 3 -w %{http_code} http://[$node]:10256/healthz -o /dev/null | grep -v 200 || true`
       if [ -n "$healthResult" ]; then
-        echo "$node kube-proxy's health check failed"
+        echo "$node kube-proxy's health check failed: /healthz responds with '$healthResult'"
         exit 1
       fi
     done
